##
## Copyright (c) 2021 - Team11. All rights reserved.
##

version: '3.7'

services:

  neo-node:
    #image: registry.team11.lv/public/neo-node:latest
    image: neo-node:latest
    container_name: neo-node
    hostname: neo-node
    build:
      dockerfile: Dockerfile
      target: production
      context: .
    ports:
      - 20331:20331
      - 20332:20332
      - 20333:20333
      - 20334:20334
    volumes:
      - neo-node-data:/neo-node-data
    command: tail -f /dev/null


volumes:
  neo-node-data: